events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    gzip on;

    upstream fastapi_app {
        server app:8000;
    }

    server {
        listen 80;
        server_name _;

        location /static/ {
            alias /app/static/;
        }

        location /health {
            proxy_pass http://fastapi_app;
            access_log off;
        }

        location / {
            proxy_pass http://fastapi_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
